spring:
  application:
    name: @project.artifactId@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/technician?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: 131474
  activiti:
    # 1、false：默认值。activiti在启动时，对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常
    # 2、true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建
    # 3、create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）
    # 4、drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
    database-schema-update: drop-create
    # 数据库历史表是否启用。默认为false，建议改为true
    db-history-used: true
    # 记录历史等级 可配置的历史级别有none, activity, audit, full
    # 1、none：    不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
    # 2、activity：级别高于none，保存流程实例与流程行为，其他数据不保存。
    # 3、audit：   除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值。
    # 4、full：    保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等。
    history-level: full
    # 校验流程文件，默认校验resources包下的processes文件夹里的流程文件
    check-process-definitions: false
    # 定义流程部署失败时的处理策略，默认是never-fail
    # 1、always：                每次启动时，都会重新部署流程文件
    # 2、single-resource：       每个资源只会被部署一次，如果资源没有变化，则不会被重新部署
    # 3、resource-parent-folder：与single-resource类似，但是以资源的父文件夹作为判断依据
    # 4、never-fail：            默认值，不会重新部署已经存在的流程文件
    deployment-mode: never-fail
    # 关闭异步执行器，默认true开启
    async-executor-activate: false

logging:
  level:
    org.activiti: debug
    com.example: debug
